version: "3"
services:

  keycloak:
    image: quay.io/keycloak/keycloak:18.0.0
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - 8080:8080
    command: "start-dev"

  casdoor:
    image: casbin/casdoor-all-in-one
    ports:
      - 8000:8000

  glewlwyd:
    image: babelouest/glewlwyd:latest
    ports:
      - 4593:4593
    stdin_open: true 
    tty: true    

  omejdn:
    image: my-omejdn-server
    ports:
      - 4567:4567
    volumes:
      - ./OAuthServers/omejdn-server/config:/opt/config
      - ./OAuthServers/omejdn-server/keys:/opt/keys

  a12n:
    image: a12n-server 
    ports:
      - 8531:8531

  scanner:
    build:
      context: ./OAuthScanner
      dockerfile: dockerfile
    environment:
      - FLASK_RUN_PORT=65432 # This overrides HOST in scanner/app.py
      - FLASK_RUN_HOST=0.0.0.0 # This overrides PORT in scanner/app.py
    ports:
      - 5000:80

  # example-with-build:
  #   build:
  #     context: example-with-build
  #     dockerfile: docker/Dockerfile
  #   environment:
  #     - FOO1=BAR2
  #     - FOO2=BAR2
  #   ports:
  #     - 8000:8000