version: "3"
services:

  scanner:
    build:
      context: .
      dockerfile: dockerfile
    environment:
      - FLASK_RUN_PORT=65432 # This overrides HOST in scanner/app.py
      - FLASK_RUN_HOST=0.0.0.0 # This overrides PORT in scanner/app.py
    ports:
      - 5000:80